### Normalizing Indicators Using Min-Max Normalization

Uses the normalize_indicator and normalize_indicator_flip functions. The flip function is to align the direction of the indicators with each other (0-1 scale).

Input: cleaned_data
Output: cleaned_normalized_data

In [1]:
import sys
import os

# get project root for python script import
project_root = os.path.abspath("..")
sys.path.append(project_root)

from scripts.normalization import normalize_indicator, normalize_indicator_flip

In [ ]:
# adult living alone
adult_living_alone = normalize_indicator_flip("adult_living_alone_data.csv", "% Householder 65 years and over living alone, 2024")
display(adult_living_alone)

,GEOID,"% Householder 65 years and over living alone, 2024","% Householder 65 years and over living alone, 2024 (normalized)"
0,13067030104,26.6,0.003802
1,13067030107,14.3,0.471483
2,13067030108,9.4,0.657795
3,13067030109,12.1,0.555133
4,13067030110,15.5,0.425856
...,...,...,...
181,13067031514,7.2,0.741445
182,13067031515,6.2,0.779468
183,13067031516,2.4,0.923954
184,13067031517,13.9,0.486692
185,13067031518,9.6,0.650190

In [ ]:
# educational attainment
edu_attainment = normalize_indicator("edu_attainment_data.csv", "% Population 25 years and over, bachelor's degree, 2024")
display(edu_attainment)

,GEOID,"% Population 25 years and over, bachelor's degree, 2024","% Population 25 years and over, bachelor's degree, 2024 (normalized)"
0,13067030104,13.7,0.189409
1,13067030107,25.7,0.433809
2,13067030108,34.0,0.602851
3,13067030109,34.1,0.604888
4,13067030110,29.3,0.507128
...,...,...,...
181,13067031514,24.6,0.411405
182,13067031515,31.9,0.560081
183,13067031516,42.5,0.775967
184,13067031517,25.6,0.431772
185,13067031518,26.1,0.441955

In [ ]:
# unemployment
unemployment = normalize_indicator_flip("unemployment_rate_data.csv", "% Unemployment Rate, 2024")
display(unemployment)

,GEOID,"% Unemployment Rate, 2024","% Unemployment Rate, 2024 (normalized)"
0,13067030104,4.8,0.758794
1,13067030107,3.2,0.839196
2,13067030108,1.7,0.914573
3,13067030109,2.9,0.854271
4,13067030110,5.3,0.733668
...,...,...,...
181,13067031514,9.6,0.517588
182,13067031515,4.2,0.788945
183,13067031516,1.5,0.924623
184,13067031517,4.8,0.758794
185,13067031518,2.3,0.884422

In [5]:
# opportunity youth
opportunity_youth = normalize_indicator_flip("opportunity_youth_data.csv", "% Disconnected youth: ages 16-19 not in school or in labor force, 2024")
display(opportunity_youth)

,GEOID,"% Disconnected youth: ages 16-19 not in school or in labor force, 2024","% Disconnected youth: ages 16-19 not in school or in labor force, 2024 (normalized)"
0,13067030104,0.0,1.000
1,13067030107,0.0,1.000
2,13067030108,1.9,0.981
3,13067030109,0.0,1.000
4,13067030110,5.6,0.944
...,...,...,...
181,13067031514,23.3,0.767
182,13067031515,0.0,1.000
183,13067031516,0.0,1.000
184,13067031517,0.0,1.000
185,13067031518,3.7,0.963

In [6]:
# rent burden
rent_burden = normalize_indicator_flip("rent_burden_data.csv", "% Gross rent 30.0 percent of income or greater, 2024")
display(rent_burden)

,GEOID,"% Gross rent 30.0 percent of income or greater, 2024","% Gross rent 30.0 percent of income or greater, 2024 (normalized)"
0,13067030104,54.0,0.460
1,13067030107,61.9,0.381
2,13067030108,62.4,0.376
3,13067030109,74.3,0.257
4,13067030110,52.9,0.471
...,...,...,...
181,13067031514,53.3,0.467
182,13067031515,21.3,0.787
183,13067031516,80.0,0.200
184,13067031517,42.3,0.577
185,13067031518,52.9,0.471

In [7]:
# renter occupied
renter_occupied = normalize_indicator_flip("renter_occupied_data.csv", "% Renter-occupied housing units, 2024")
display(renter_occupied)

,GEOID,"% Renter-occupied housing units, 2024","% Renter-occupied housing units, 2024 (normalized)"
0,13067030104,48.2,0.521127
1,13067030107,17.8,0.826962
2,13067030108,11.7,0.888330
3,13067030109,32.4,0.680080
4,13067030110,29.0,0.714286
...,...,...,...
181,13067031514,10.7,0.898390
182,13067031515,5.3,0.952716
183,13067031516,15.4,0.851107
184,13067031517,25.5,0.749497
185,13067031518,14.6,0.859155

In [8]:
# median home value
median_home_value = normalize_indicator("median_home_value_data.csv", "Median value of owner-occupied unit (dollars), 2024")
display(median_home_value)

,GEOID,"Median value of owner-occupied unit (dollars), 2024","Median value of owner-occupied unit (dollars), 2024 (normalized)"
0,13067030104,330400.0,0.199914
1,13067030107,360600.0,0.232391
2,13067030108,530000.0,0.414561
3,13067030109,382600.0,0.256049
4,13067030110,365300.0,0.237445
...,...,...,...
181,13067031514,322200.0,0.191096
182,13067031515,414200.0,0.290031
183,13067031516,415400.0,0.291322
184,13067031517,398400.0,0.273040
185,13067031518,329600.0,0.199054

In [9]:
# eviction
eviction = normalize_indicator_flip("eviction_data.csv", "Eviction Filing Rate")
display(eviction)

         TractID  Eviction Filing Rate  Eviction Filing Rate (normalized)
0    13067030412               0.01870                           0.642051
1    13067031405               0.00574                           0.907897
2    13067031101               0.01740                           0.668718
3    13067031505               0.00914                           0.838154
4    13067031116               0.02570                           0.498462
..           ...                   ...                                ...
98   13067031311               0.03010                           0.408205
99   13067031503               0.01560                           0.705641
100  13067030411               0.02170                           0.580513
101  13067031112               0.01590                           0.699487
102  13067030215               0.00556                           0.911590

[103 rows x 3 columns]

In [10]:
# no health insurance
no_health_insurance = normalize_indicator_flip("no_health_ins_data.csv", "% Civilian non-institutionalized population, no health insurance, 2024")
display(no_health_insurance)

,GEOID,"% Civilian non-institutionalized population, no health insurance, 2024","% Civilian non-institutionalized population, no health insurance, 2024 (normalized)"
0,13067030104,17.8,0.633540
1,13067030107,9.2,0.811594
2,13067030108,18.0,0.629400
3,13067030109,8.6,0.824017
4,13067030110,15.3,0.685300
...,...,...,...
181,13067031514,15.7,0.677019
182,13067031515,9.5,0.805383
183,13067031516,8.6,0.824017
184,13067031517,17.1,0.648033
185,13067031518,17.0,0.650104

In [8]:
# obesity
obesity = normalize_indicator_flip("transp_obesity_data.csv", "Obesity among adults", "obesity_data.csv")
obesity = obesity.iloc[:, [0, 2, 3]]
display(obesity)
obesity.to_csv("../cleaned_normalized_data/obesity_data.csv", index=False)

     LocationName  Obesity among adults  Obesity among adults (normalized)
0     13067030104                  31.4                           0.519553
1     13067030107                  28.7                           0.670391
2     13067030108                  27.4                           0.743017
3     13067030109                  27.0                           0.765363
4     13067030110                  30.4                           0.575419
..            ...                   ...                                ...
181   13067031514                  32.9                           0.435754
182   13067031515                  30.5                           0.569832
183   13067031516                  31.9                           0.491620
184   13067031517                  30.5                           0.569832
185   13067031518                  36.1                           0.256983

[186 rows x 3 columns]

In [10]:
# transportation
transportation = normalize_indicator_flip("transp_obesity_data.csv", "Lack of reliable transportation in the past 12 months among adults", "transp_data.csv")
transportation = transportation.iloc[:, [0, 1, 3]]
display(transportation)
transportation.to_csv("../cleaned_normalized_data/transp_data.csv", index=False)

,LocationName,Lack of reliable transportation in the past 12 months among adults,Lack of reliable transportation in the past 12 months among adults (normalized)
0,13067030104,8.6,0.644578
1,13067030107,6.7,0.759036
2,13067030108,5.3,0.843373
3,13067030109,5.6,0.825301
4,13067030110,8.5,0.650602
...,...,...,...
181,13067031514,8.9,0.626506
182,13067031515,6.7,0.759036
183,13067031516,7.3,0.722892
184,13067031517,7.1,0.734940
185,13067031518,10.9,0.506024

In [11]:
# not good mental health
not_good_mental_health = normalize_indicator_flip("not_good_mental_health_data.csv", "E_MHLTH")
display(not_good_mental_health)

           GEOID  E_MHLTH  E_MHLTH (normalized)
0    13067030107     14.8              0.602941
1    13067030250     13.4              0.705882
2    13067030251     13.6              0.691176
3    13067030254     17.6              0.397059
4    13067030262     13.0              0.735294
..           ...      ...                   ...
181  13067030910     18.1              0.360294
182  13067031318     20.3              0.198529
183  13067031324     15.7              0.536765
184  13067031416     18.2              0.352941
185  13067031507     15.8              0.529412

[186 rows x 3 columns]

In [12]:
# no vehicle
no_vehicle = normalize_indicator_flip("no_vehicle_data.csv", "% Occupied housing units, no vehicles available, 2024")
display(no_vehicle)

,GEOID,"% Occupied housing units, no vehicles available, 2024","% Occupied housing units, no vehicles available, 2024 (normalized)"
0,13067030104,15.1,0.322870
1,13067030107,1.3,0.941704
2,13067030108,0.0,1.000000
3,13067030109,1.3,0.941704
4,13067030110,7.9,0.645740
...,...,...,...
181,13067031514,0.6,0.973094
182,13067031515,2.4,0.892377
183,13067031516,2.2,0.901345
184,13067031517,4.7,0.789238
185,13067031518,1.6,0.928251

In [14]:
# travel time to work
travel_time_to_work = normalize_indicator_flip("travel_to_work_data_calculated.csv", "Mean travel time to work (minutes), 2024", "travel_time_to_work_data.csv")
travel_time_to_work = travel_time_to_work.iloc[:, [0, 1, 3]]
display(travel_time_to_work)
travel_time_to_work.to_csv("../cleaned_normalized_data/travel_time_to_work_data.csv", index=False)

,GEOID,"Mean travel time to work (minutes), 2024","Mean travel time to work (minutes), 2024 (normalized)"
0,13067030104,31.8,0.465455
1,13067030107,30.2,0.523636
2,13067030108,28.4,0.589091
3,13067030109,36.6,0.290909
4,13067030110,31.0,0.494545
...,...,...,...
181,13067031514,33.2,0.414545
182,13067031515,33.3,0.410909
183,13067031516,34.2,0.378182
184,13067031517,34.0,0.385455
185,13067031518,34.5,0.367273

In [17]:
# alternative transp to work
alt_transp_to_work = normalize_indicator_flip("travel_to_work_data_calculated.csv", "alt_transport_pct", "alt_transp_to_work_data.csv")
alt_transp_to_work = alt_transp_to_work.iloc[:, [0, 2, 3]]
display(alt_transp_to_work)
alt_transp_to_work.to_csv("../cleaned_normalized_data/alt_transp_to_work_data.csv", index=False)

           GEOID  alt_transport_pct  alt_transport_pct (normalized)
0    13067030104          18.544474                        0.356868
1    13067030107           8.864579                        0.692572
2    13067030108           4.832536                        0.832405
3    13067030109          11.529185                        0.600162
4    13067030110           7.270560                        0.747853
..           ...                ...                             ...
181  13067031514           5.420827                        0.812003
182  13067031515           2.742708                        0.904881
183  13067031516           3.458557                        0.880055
184  13067031517          10.619469                        0.631711
185  13067031518           8.530084                        0.704172

[186 rows x 3 columns]

In [18]:
# preschool enroll
preschool_enroll = normalize_indicator("preschool_enroll_data.csv", "% Enrolled in nursery school, preschool, 2024")
display(preschool_enroll)

,GEOID,"% Enrolled in nursery school, preschool, 2024","% Enrolled in nursery school, preschool, 2024 (normalized)"
0,13067030104,7.3,0.308017
1,13067030107,2.2,0.092827
2,13067030108,4.0,0.168776
3,13067030109,0.0,0.000000
4,13067030110,13.1,0.552743
...,...,...,...
181,13067031514,5.0,0.210970
182,13067031515,10.0,0.421941
183,13067031516,4.9,0.206751
184,13067031517,2.3,0.097046
185,13067031518,0.0,0.000000

In [19]:
# single parent fam
single_parent_fam = normalize_indicator_flip("single_parent_fam_data.csv", "% Single parent families with own children of the householder, 2024")
display(single_parent_fam)

,GEOID,"% Single parent families with own children of the householder, 2024","% Single parent families with own children of the householder, 2024 (normalized)"
0,13067030104,7.7,0.794667
1,13067030107,7.7,0.794667
2,13067030108,6.1,0.837333
3,13067030109,7.2,0.808000
4,13067030110,13.8,0.632000
...,...,...,...
181,13067031514,5.7,0.848000
182,13067031515,1.3,0.965333
183,13067031516,12.8,0.658667
184,13067031517,20.7,0.448000
185,13067031518,9.3,0.752000

In [20]:
# child grandparent
child_grandparent = normalize_indicator_flip("child_grandparent_data.csv", "% Children raised by grandparent, 2024")
display(child_grandparent)

,GEOID,"% Children raised by grandparent, 2024","% Children raised by grandparent, 2024 (normalized)"
0,13067030104,0.0,1.000000
1,13067030107,0.0,1.000000
2,13067030108,5.2,0.799228
3,13067030109,22.7,0.123552
4,13067030110,0.0,1.000000
...,...,...,...
181,13067031514,4.6,0.822394
182,13067031515,0.8,0.969112
183,13067031516,4.7,0.818533
184,13067031517,5.9,0.772201
185,13067031518,0.5,0.980695