### Data Extraction for EJI Data

In [1]:
import pandas as pd

df = pd.read_csv('../raw_data/17_EJI_2024_Georgia.csv')

In [5]:
# filter for Cobb County
cobb_df = df[df['COUNTY'] == 'Cobb County']
display(cobb_df.head())

,STATEFP,COUNTYFP,TRACTCE,AFFGEOID,GEOID,GEOID_2020,COUNTY,StateDesc,STATEABBR,LOCATION,...,E_AIAN,NHPI,E_NHPI,TWOMORE,E_TWOMORE,OTHERRACE,E_OTHERRACE,Tribe_PCT_Tract,Tribe_Names,Tribe_Flag
20,13,67,30107,140000US13067030107,13067030107,13067030107,Cobb County,Georgia,GA,Census Tract 301.07; Cobb County; Georgia,...,0.0,0,0.0,130,2.7,5,0.1,0.0,-999,-999
159,13,67,30250,140000US13067030250,13067030250,13067030250,Cobb County,Georgia,GA,Census Tract 302.50; Cobb County; Georgia,...,0.0,0,0.0,225,4.1,39,0.7,0.0,-999,-999
200,13,67,30251,140000US13067030251,13067030251,13067030251,Cobb County,Georgia,GA,Census Tract 302.51; Cobb County; Georgia,...,0.1,0,0.0,312,9.9,40,1.3,0.0,-999,-999
201,13,67,30254,140000US13067030254,13067030254,13067030254,Cobb County,Georgia,GA,Census Tract 302.54; Cobb County; Georgia,...,0.0,0,0.0,44,2.4,0,0.0,0.0,-999,-999
202,13,67,30262,140000US13067030262,13067030262,13067030262,Cobb County,Georgia,GA,Census Tract 302.62; Cobb County; Georgia,...,0.0,0,0.0,271,5.6,0,0.0,0.0,-999,-999

In [ ]:
# select relevant columns
# E_MHLTH = % of individuals reporting not good mental health
cobb_df = cobb_df[['GEOID', 'E_MHLTH']]
display(cobb_df)

            GEOID  E_MHLTH
20    13067030107     14.8
159   13067030250     13.4
200   13067030251     13.6
201   13067030254     17.6
202   13067030262     13.0
...           ...      ...
1623  13067030910     18.1
1689  13067031318     20.3
1690  13067031324     15.7
1691  13067031416     18.2
1692  13067031507     15.8

[186 rows x 2 columns]

In [10]:
# save cleaned data to csv
cobb_df.to_csv('../cleaned_data/not_good_mental_health_data.csv', index=False)