In [4]:
import pandas as pd

df = pd.read_csv('../raw_data/19_Eviction-Filings-by-Census-Tract-12_01_2023-2020-Cobb_County.csv')
display(df.head())

       TractID       Month  Total Eviction Filings  Eviction Filing Rate
0  13067030412  12/01/2023                      31               0.01870
1  13067031405  12/01/2023                       5               0.00574
2  13067031101  12/01/2023                      20               0.01740
3  13067031505  12/01/2023                       7               0.00914
4  13067031116  12/01/2023                      21               0.02570

In [5]:
# select relevant columns (eviction filing rate)
eviction_df = df[['TractID', 'Eviction Filing Rate']]
display(eviction_df)

         TractID  Eviction Filing Rate
0    13067030412               0.01870
1    13067031405               0.00574
2    13067031101               0.01740
3    13067031505               0.00914
4    13067031116               0.02570
..           ...                   ...
98   13067031311               0.03010
99   13067031503               0.01560
100  13067030411               0.02170
101  13067031112               0.01590
102  13067030215               0.00556

[103 rows x 2 columns]

In [6]:
# save cleaned data to csv
eviction_df.to_csv('../cleaned_data/eviction_data.csv', index=False)