### Data Cleaning for PLACES Data

In [1]:
import pandas as pd

In [ ]:
# for the lack of reliable transportation and obesity data
transp_obesity_data = pd.read_csv("../raw_data/3_PLACES__Local_Data_for_Better_Health,_Census_Tract_Data,_2025_release_20260330.csv")
display(transp_obesity_data)

,Year,StateAbbr,StateDesc,CountyName,CountyFIPS,LocationName,DataSource,Category,Measure,Data_Value_Unit,...,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,TotalPop18plus,Geolocation,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text
0,2023,GA,Georgia,Cobb,13067,13067031221,BRFSS,Health Outcomes,Obesity among adults,%,...,23.3,31.7,"3,488","2,737",POINT (-84.5088667 33.833725),13067031221,HLTHOUT,OBESITY,CrdPrv,Obesity
1,2023,GA,Georgia,Cobb,13067,13067031511,BRFSS,Health Outcomes,Obesity among adults,%,...,28.6,38.3,"5,638","4,321",POINT (-84.7122347 33.858756),13067031511,HLTHOUT,OBESITY,CrdPrv,Obesity
2,2023,GA,Georgia,Cobb,13067,13067030244,BRFSS,Health Outcomes,Obesity among adults,%,...,21.8,30.1,"4,722","3,491",POINT (-84.6885166 33.9981062),13067030244,HLTHOUT,OBESITY,CrdPrv,Obesity
3,2023,GA,Georgia,Cobb,13067,13067030242,BRFSS,Health-Related Social Needs,Lack of reliable transportation in the past 12...,%,...,5.8,7.9,"4,367","3,350",POINT (-84.636262 34.0154255),13067030242,SOCLNEED,LACKTRPT,CrdPrv,Transportation Barriers
4,2023,GA,Georgia,Cobb,13067,13067030113,BRFSS,Health-Related Social Needs,Lack of reliable transportation in the past 12...,%,...,8.2,10.8,"4,124","3,041",POINT (-84.6391776 34.0680926),13067030113,SOCLNEED,LACKTRPT,CrdPrv,Transportation Barriers
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
367,2023,GA,Georgia,Cobb,13067,13067030800,BRFSS,Health-Related Social Needs,Lack of reliable transportation in the past 12...,%,...,10.5,14.7,"5,617","4,861",POINT (-84.5258982 33.9397344),13067030800,SOCLNEED,LACKTRPT,CrdPrv,Transportation Barriers
368,2023,GA,Georgia,Cobb,13067,13067030347,BRFSS,Health-Related Social Needs,Lack of reliable transportation in the past 12...,%,...,5.6,7.3,"4,885","3,711",POINT (-84.5458621 34.0716402),13067030347,SOCLNEED,LACKTRPT,CrdPrv,Transportation Barriers
369,2023,GA,Georgia,Cobb,13067,13067031118,BRFSS,Health-Related Social Needs,Lack of reliable transportation in the past 12...,%,...,5.5,7.6,"5,993","4,432",POINT (-84.5269135 33.8554556),13067031118,SOCLNEED,LACKTRPT,CrdPrv,Transportation Barriers
370,2023,GA,Georgia,Cobb,13067,13067030352,BRFSS,Health Outcomes,Obesity among adults,%,...,20.5,28.8,"5,308","4,031",POINT (-84.4272688 33.9369194),13067030352,HLTHOUT,OBESITY,CrdPrv,Obesity
371,2023,GA,Georgia,Cobb,13067,13067031306,BRFSS,Health Outcomes,Obesity among adults,%,...,31.4,41.4,"4,176","3,162",POINT (-84.5907695 33.827175),13067031306,HLTHOUT,OBESITY,CrdPrv,Obesity

In [ ]:
transp_obesity_subset = transp_obesity_data[["LocationName", "Measure", "Data_Value", "TotalPop18plus"]]
display(transp_obesity_subset)

,LocationName,Measure,Data_Value,TotalPop18plus
0,13067031221,Obesity among adults,27.4,"2,737"
1,13067031511,Obesity among adults,33.3,"4,321"
2,13067030244,Obesity among adults,25.6,"3,491"
3,13067030242,Lack of reliable transportation in the past 12...,6.8,"3,350"
4,13067030113,Lack of reliable transportation in the past 12...,9.5,"3,041"
...,...,...,...,...
367,13067030800,Lack of reliable transportation in the past 12...,12.5,"4,861"
368,13067030347,Lack of reliable transportation in the past 12...,6.4,"3,711"
369,13067031118,Lack of reliable transportation in the past 12...,6.5,"4,432"
370,13067030352,Obesity among adults,24.4,"4,031"
371,13067031306,Obesity among adults,36.2,"3,162"

In [ ]:
# pivot table to have each indicator be a column
transp_obesity_wide = (
    transp_obesity_subset
    .pivot(index=["LocationName", "TotalPop18plus"], columns="Measure", values="Data_Value")
    .reset_index()
)

display(transp_obesity_wide)

transp_obesity_wide.to_csv("../cleaned_data/transp_obesity_data.csv", index=False)

Measure,LocationName,TotalPop18plus,Lack of reliable transportation in the past 12 months among adults,Obesity among adults
0,13067030104,"3,143",8.6,31.4
1,13067030107,"3,933",6.7,28.7
2,13067030108,"3,773",5.3,27.4
3,13067030109,"2,752",5.6,27.0
4,13067030110,"3,744",8.5,30.4
...,...,...,...,...
181,13067031514,"2,070",8.9,32.9
182,13067031515,"3,144",6.7,30.5
183,13067031516,"1,858",7.3,31.9
184,13067031517,"2,852",7.1,30.5
185,13067031518,"2,205",10.9,36.1